site_name: SASjs Server
site_url: https://server.sasjs.io
nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide:
      - Authorisation: auth.md
      - App Stream: apps.md
      - SASjs Studio: studio.md
  - Developer Guide:
      - API: /api/index.html
      - Sessions: sessions.md
      - Stored Programs: storedprograms.md
  - Admin Guide:
      - Permissions: permissions.md
      - Settings: settings.md
  - FAQ: faq.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - codehilite
  - meta
  - toc:
      permalink: true

extra_css: ['font-awesome.css']

plugins:
  - search:
      prebuild_index: true

# Repository
repo_name: 'server.sasjs.io'
repo_url: 'https://github.com/sasjs/server.sasjs.io'
repo_branch: 'main'
edit_uri: 'edit/main/docs/'

theme:
  name: material
  logo: 'img/logo/favicon/32.png'
  palette:
    primary: 'White'
    accent: 'Amber'
  font:
    text: 'Open Sans'
    code: 'Ubuntu Mono'
  favicon: img/logo/favicon/32.ico
  custom_dir: 'theme'
  highlightjs: true
  hljs_languages:
    - SAS
    - JavaScript
    - Bash
  extra:
    social:
      - icon: fontawesome/brands/linkedin
        link: https://linkedin.com/company/sasjs
        name: SASjs on LinkedIn
copyright: All rights reserved &copy;2021 Macro People Ltd.

google_analytics: ['UA-109713029-8', 'sasjs.io']
