name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.16
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CUSTOM_DOMAIN: server.sasjs.io

  slides:
    name: Generate and push slides
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy over swagger docs
        run: cp -R theme/api api
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit and push
        uses: EndBug/add-and-commit@v5
        with:
          branch: gh-pages
          message: 'Update branch'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
